<a href="https://colab.research.google.com/github/nish700/Computer-Vision-and-Deep-learning/blob/master/Pytorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import numpy as np
import matplotlib.pyplot as plt

#Initialise Tensor


In [0]:
## this section contains code to initialize variables using torch

In [2]:
x = torch.ones(3,2)
print(x)
x = torch.zeros(3,2)
print(x)
x = torch.randn(3,2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[ 1.1245, -1.1017],
        [ 1.6710,  0.0963],
        [-0.4301,  0.0740]])


In [3]:
x = torch.empty(3,2)
print(x)
y = torch.zeros_like(x)
print(y)

tensor([[2.9974e-36, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [4]:
x = torch.linspace(0,1,steps=5)
print(x)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [5]:
x = torch.tensor([[1,2],[3,4],[5,6]])
print(x)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


#Slicing tensor

In [0]:
##this section contains the code sample to slice the tensor variables , its just like we do for numpy variables

In [6]:
print(x.size())
print(x[:,0])
print(x[0,:])

torch.Size([3, 2])
tensor([1, 3, 5])
tensor([1, 2])


In [7]:
y = x[1,1]
print(y)
print(y.item())

tensor(4)
4


#Reshaping Tensors

In [0]:
## this section contains the sample for reshaping tensor to desired shape

In [8]:
print(x)
y = x.view(2,3)
print(y)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [9]:
y = x.view(6,-1)
print(y)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


#Simple Tensor Operations

In [0]:
## this section contains simple tensor operations such as addition , substraction and multiplication

In [10]:
x = torch.ones(3,2)
y = torch.ones(3,2)
print(x)
print(y)
z_1 = x + y
print(z_1)
z_2 = x - y 
print(z_2)
z_3 = x * y
print(z_3)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [11]:
z = y.add(x)
print(z)
print(y)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [12]:
z = y.add_(x)##inplace=True
print(z)
print(y)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


#Numpy Vs Pytorch

In [0]:
## this section contains the code sample to change the dtype from numpy to tensor and vice versa. 
#Its also compares the performance of similar codes on numpy and tensor framework.

In [13]:
x_np = x.numpy()
print(type(x),type(x_np))
print(x_np)

<class 'torch.Tensor'> <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [14]:
a = np.random.randn(5)
print(a)
a_pt = torch.from_numpy(a)
print(type(a),type(a_pt))
print(a_pt)

[-1.529153    0.41464487 -0.11181268 -1.36918293  0.10840957]
<class 'numpy.ndarray'> <class 'torch.Tensor'>
tensor([-1.5292,  0.4146, -0.1118, -1.3692,  0.1084], dtype=torch.float64)


In [15]:
np.add(a,1,out=a)
print(a)
print(a_pt)

[-0.529153    1.41464487  0.88818732 -0.36918293  1.10840957]
tensor([-0.5292,  1.4146,  0.8882, -0.3692,  1.1084], dtype=torch.float64)


In [16]:
%%time
for i in range(100):
  a = np.random.randn(100,100)
  b = np.random.randn(100,100)
  c = np.matmul(a,b)
print(c)

[[  3.80733494  -4.55343484   5.48870953 ...  -1.69908167   1.50165632
    3.39003255]
 [ -9.08159705  -3.58928305  22.80486667 ...  -2.69392897  -6.1807819
   11.92088218]
 [  8.0632236    6.94513914  -8.23384979 ...  12.55348756   3.75028073
    0.99504804]
 ...
 [ 17.85483337  -0.1379174  -15.16342765 ...  -8.51883302  -1.11310804
    5.68613497]
 [ 14.06364629  11.56702395  11.63457084 ...  -5.15904475  21.63143744
    4.10795904]
 [-14.55709993  -9.74030858   0.98112939 ...   2.23031321   1.00947238
  -20.47090458]]
CPU times: user 151 ms, sys: 81.2 ms, total: 232 ms
Wall time: 127 ms


In [17]:
%%time
for i in range(100):
  a = torch.randn([100,100])
  b = torch.randn([100,100])
  c = torch.matmul(a,b)
print(c)

tensor([[ -5.4587,  23.6062,   2.5742,  ...,   8.6225,   1.9145,  -8.9148],
        [-13.2948,  -1.3387,  12.6494,  ...,  -1.5454,  -3.6752,  -7.8591],
        [ -3.2499, -19.6330,   7.8971,  ...,   7.8810,  -9.7527,   6.0241],
        ...,
        [  5.0440, -21.5526,  -9.7747,  ...,  21.7456,   6.5434,   7.9459],
        [ 10.1167,  -4.3353, -10.4853,  ...,  -7.4252,  -8.0626,  -2.6525],
        [  6.1640,  11.4137,   4.8035,  ...,   6.5914,   3.4598, -15.7465]])
CPU times: user 24.2 ms, sys: 652 µs, total: 24.9 ms
Wall time: 48.2 ms


In [18]:
%%time
for i in range(1000):
  a = np.random.randn(1000,1000)
  b = np.random.randn(1000,1000)
  c = a + b

CPU times: user 1min 21s, sys: 62.5 ms, total: 1min 21s
Wall time: 1min 21s


In [19]:
%%time
for i in range(1000):
  a = torch.randn([1000,1000])
  b = torch.randn([1000,1000])
  c = a + b

CPU times: user 13.4 s, sys: 68.2 ms, total: 13.5 s
Wall time: 13.5 s


In [20]:
%%time
for i in range(1000):
  a = np.random.randn(1000,1000)
  b = np.random.randn(1000,1000)
  c = a * b

CPU times: user 1min 21s, sys: 89.9 ms, total: 1min 21s
Wall time: 1min 21s


In [21]:
%%time
for i in range(1000):
  a = torch.randn([1000,1000])
  b = torch.randn([1000,1000])
  c = a * b

CPU times: user 13.5 s, sys: 60 ms, total: 13.6 s
Wall time: 13.6 s


#CUDA suppport

In [0]:
## this section compares the performance of tensor on CPU with the tensor on GPU. the tensor on GPU shows 3 fold increase in performace.
##  as compared to numpy , gives almost 10 fold increase in speed

In [22]:
print(torch.cuda.device_count())

1


In [23]:
print(torch.cuda.device(0))

In [24]:
print(torch.cuda.get_device_name(0))

Tesla P4


In [0]:
cuda0 = torch.device('cuda:0')

In [27]:
%%time
a = torch.ones(3,2, device=cuda0)
b = torch.ones(3,2, device=cuda0)
c = a + b
print(c)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]], device='cuda:0')
CPU times: user 3.95 ms, sys: 1.02 ms, total: 4.97 ms
Wall time: 35 ms


In [28]:
print(a)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], device='cuda:0')


In [29]:
%%time
for i in range(100):
  a = np.random.randn(100,100)
  b = np.random.randn(100,100)
  c= np.add(a,b)

CPU times: user 83.3 ms, sys: 1.99 ms, total: 85.3 ms
Wall time: 94.5 ms


In [30]:
%%time
for i in range(100):
  a = torch.randn([100,100])
  b = torch.randn([100,100])
  b.add_(a)

CPU times: user 18 ms, sys: 1.99 ms, total: 20 ms
Wall time: 22.3 ms


In [31]:
%%time
for i in range(100):
  a = torch.randn([100,100], device=cuda0)
  b = torch.randn([100,100], device=cuda0)
  b.add_(a)

CPU times: user 3.87 ms, sys: 8 µs, total: 3.88 ms
Wall time: 8.23 ms


In [32]:
%%time
for i in range(1000):
  a = np.random.randn(1000,1000)
  b = np.random.randn(1000,1000)
  c = np.matmul(a,b)

CPU times: user 3min 25s, sys: 1min 21s, total: 4min 47s
Wall time: 2min 25s


In [33]:
%%time
for i in range(1000):
  a = torch.randn([1000,1000])
  b = torch.randn([1000,1000])
  c = torch.matmul(a,b)

CPU times: user 27.3 s, sys: 158 ms, total: 27.4 s
Wall time: 27.4 s


In [34]:
%%time
for i in range(1000):
  a = torch.randn([1000,1000], device=cuda0)
  b = torch.randn([1000,1000], device=cuda0)
  c = torch.matmul(a,b)

CPU times: user 282 ms, sys: 183 ms, total: 465 ms
Wall time: 465 ms


# AutoGrad

In [0]:
## this section contains code samples to implement auto gradient in pytorch

In [36]:
x = torch.ones([3,2],requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)


In [37]:
y = x + 5
print(y)

tensor([[6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)


In [38]:
z = y**2 + 1
print(z)

tensor([[37., 37.],
        [37., 37.],
        [37., 37.]], grad_fn=<AddBackward0>)


In [39]:
t = torch.sum(z)
print(t)

tensor(222., grad_fn=<SumBackward0>)


In [0]:
t.backward()

In [42]:
print(x.grad)

tensor([[12., 12.],
        [12., 12.],
        [12., 12.]])


In [44]:
print(z.grad)

None


In [47]:
x = torch.ones([3,2], requires_grad=True)
print(x)
y = x + 5
print(y)
r = 1 / (1 + torch.exp(-y))
print(r)
s = torch.sum(r)
print(s)
s.backward()
print(x.grad)
## f(x)(1-f(x))

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)
tensor([[0.9975, 0.9975],
        [0.9975, 0.9975],
        [0.9975, 0.9975]], grad_fn=<MulBackward0>)
tensor(5.9852, grad_fn=<SumBackward0>)
tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])


In [49]:
x = torch.ones([3,2], requires_grad=True)
y = x + 5
r = 1/(1 + torch.exp(-y))
a = torch.ones([3,2])
r.backward(a)
print(x.grad)

tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])


#AutoDiff examples

In [0]:
# this section contains code sample to implement backward propagation and calculate the gradient w.r.t w and b using pytorch

In [53]:
x = torch.randn(3,4)
y = torch.randn([3,4])
print(y)
print(x)

tensor([[ 1.2777, -0.0935, -0.8347, -0.9409],
        [ 0.1342,  0.4996, -0.1175,  0.4126],
        [ 1.6697,  0.8942,  0.3227,  0.7073]])
tensor([[ 2.0023, -0.8934, -0.1259, -1.8558],
        [-1.6388, -0.4193, -0.0171, -1.5940],
        [-0.2247,  1.5901,  0.7409, -1.3532]])


In [0]:
x = torch.randn([20,1],requires_grad=True)
y = 3*x-2

In [0]:
w = torch.tensor([1.],requires_grad=True)
b = torch.tensor([1.],requires_grad=True)

y_hat = w*x + b

loss = torch.sum((y_hat - y)**2)

In [56]:
print(loss)

tensor(334.8817, grad_fn=<SumBackward0>)


In [0]:
loss.backward()

In [58]:
print(w.grad, b.grad)

tensor([-127.1854]) tensor([138.4642])


# Do it in loop

In [0]:
## this section contains code sample to implement backward propogation and calculating the gradient inside a loop

In [61]:
learning_rate = 0.01

w = torch.tensor([1.], requires_grad=True)
b = torch.tensor([1.], requires_grad=True)

print(w.item(),b.item())

for i in range(100):
  x = torch.randn([20,1], requires_grad=True)
  y = 3*x - 2

  y_hat = w*x + b

  loss = torch.sum((y_hat - y)**2)

  loss.backward()

  with torch.no_grad():
    w -= learning_rate * w.grad
    b -= learning_rate * b.grad
  
    w.grad.zero_()
    b.grad.zero_()

  print(w.item(),b.item())

1.0 1.0
1.3653686046600342 -0.20183420181274414
2.163545608520508 -0.9534950852394104
2.6697046756744385 -1.4865671396255493
2.8838067054748535 -1.7623467445373535
2.900139808654785 -1.8499082326889038
2.934882640838623 -1.9178310632705688
2.9628794193267822 -1.9464858770370483
2.9838085174560547 -1.9743738174438477
2.990326166152954 -1.9831805229187012
2.9930920600891113 -1.9898134469985962
2.9947290420532227 -1.993674397468567
2.996565103530884 -1.9961423873901367
2.9975526332855225 -1.997622013092041
2.997821092605591 -1.998042345046997
2.998828411102295 -1.9990679025650024
2.9989993572235107 -1.9993088245391846
2.9994194507598877 -1.999682903289795
2.9996960163116455 -1.9998438358306885
2.9997994899749756 -1.9998881816864014
2.9999022483825684 -1.9999586343765259
2.999927282333374 -1.9999706745147705
2.999958038330078 -1.9999847412109375
2.9999775886535645 -1.9999871253967285
2.999980926513672 -1.9999891519546509
2.999992609024048 -1.9999943971633911
2.9999964237213135 -1.999997258

# do it for large problem

In [0]:
## this section contains code sample to implement backwward propogation for large datasets and comapres the performace 
##difference by implementing the same using GPU

In [71]:
%%time

learning_rate = 0.001
N = 10000000
epochs=200

w = torch.randn([N], requires_grad=True)
b = torch.ones([1], requires_grad=True)

for i in range(epochs):
  x = torch.randn([N], requires_grad = True)
  y = torch.dot(3 * torch.ones([N]),x) - 2

  y_hat = torch.dot(w,x) + b

  loss = torch.sum((y_hat - y)**2)

  loss.backward()

  with torch.no_grad():
    w-= learning_rate * w.grad
    b-= learning_rate * b.grad

    w.grad.zero_()
    b.grad.zero_()

CPU times: user 31.6 s, sys: 439 ms, total: 32.1 s
Wall time: 32.2 s


In [72]:
%%time

learning_rate = 0.001
N = 10000000
epochs = 200

w = torch.randn([N], requires_grad=True , device= cuda0)
b = torch.ones([1], requires_grad=True , device = cuda0)

for i in range(epochs):
  x = torch.randn([N], requires_grad = True, device= cuda0)
  y = torch.dot(3 * torch.ones([N], device= cuda0),x) - 2
  
  y_hat = torch.dot(w,x) + b

  loss = torch.sum((y_hat - y)**2)

  loss.backward()

  with torch.no_grad():
    w -= learning_rate * w.grad
    b -= learning_rate * b.grad

    w.grad.zero_()
    b.grad.zero_()

CPU times: user 908 ms, sys: 587 ms, total: 1.5 s
Wall time: 1.51 s
